### ISSUE TITLE
Update dependency to gopkg.in/manyminds/api2go.v0 or do not use content marshalers

### ISSUE THREAD

**Issue by hnakamur** [manyminds/api2go-adapter#3]
I saw the [attention at the README of api2go](https://github.com/manyminds/api2go#attention---manual-migration-required) and know content marshalers are deleted.
However api2go-adapter/gingonic still uses `api2go.DefaultContentMarshalers` and `import "github.com/manyminds/api2go"`.

Do you have a plan to update api2go-adapter/gingonic to stop using content marshalers?
If not, please change `import "github.com/manyminds/api2go"` to `import "gopkg.in/manyminds/api2go.v0"`.

Thanks!

**Comment by wwwdata** [comment]
it's only in the test right? we should remove it.

**Comment by sharpner** [comment]
I'm on it, thx!

**Comment by hnakamur** [comment]
Thanks!
