### ISSUE TITLE
Cannot use notAllowedHandler (type http.Handler) as type http.HandlerFunc

### ISSUE THREAD

**Issue by twisted1919** [manyminds/api2go-adapter#5]
I am getting below error while trying the gingonic adapter:

```
$ go get github.com/manyminds/api2go-adapter/gingonic
# github.com/manyminds/api2go/routing
../github.com/manyminds/api2go/routing/httprouter.go:51: cannot use notAllowedHandler (type http.Handler) as type http.HandlerFunc in assignment: need type assertion 
```

**Comment by wwwdata** [comment]
hi, are you sure that all your dependencies are up to date as well? Especially the api2go version should be from the current master because we have changed a lot recently.

**Comment by twisted1919** [comment]
I just `go get github.com/manyminds/api2go` after removing the entire `manyminds` folder from src and the same error. Not sure if that's of any help.

**Comment by twisted1919** [comment]
Seems that https://github.com/manyminds/api2go/blob/master/routing/httprouter.go#L51 contains same code where a simple `router.MethodNotAllowed = notAllowedHandler.(http.HandlerFunc)` casting fixes the issue.

**Comment by wwwdata** [comment]
worked for me, maybe there is another dependency that is not up to date? Do you have an outdated httprouter installed that could cause this problem? Please run `go get -u -v -t` inside the `manyminds/api2go-adapter/gingonic` directory. That should fix stuff. Our tests are running, on my local machine and on travis, that means it's working and must be an issue on your machine

**Comment by twisted1919** [comment]
gotcha, seems that i was having some outdated packages, my bad, sorry for the hassle.

**Comment by wwwdata** [comment]
no problem, this really is a typical mistake I also did when I started with go :)
