### ISSUE TITLE
What is the purpose of adapters?

### ISSUE THREAD

**Issue by abrykajlo** [manyminds/api2go-adapter#6]
Hey I have been alotted time from my company to finally work on this issue in api2go manyminds/api2go#230. Since api2go adapter is tightly coupled I am curious of the goal of this project in the scheme of things. I assume it is to allow converting a current web server to have jsonapi support. I have been having difficulties implementing what I want and was curious if you would be ok with the following:
- having two routers as part of the final router: one that allows access to the context and the other which is any router the user chooses to use
- having a custom middleware which diverts traffic to either of these two routers

I have been finding it quite difficult to support non context handlers with contexting

Thoughts?

**Comment by sharpner** [comment]
The actually goal is exactly as you described it. 
The possibility to use api2go with either framework you like, gin, mux, a propietary one and so on..

I don't think having two routers is a good solution. It will make it unecessary complex for users to handle, and additionally it adds overhead to actual lightweight routers such as juliens.

I have no idea about the way you want your solution to work, but the loop that calls middlewares can simply check if a middleware implements an optional interface 

``` go
SetContext(c Context)
```

doesn't it?

**Comment by abrykajlo** [comment]
I will find a solution with one router. The issue is that a context need not necessarily be the same every time for the router, the context is on a per user basis. For example we use a middleware which authenticates the user and puts their profile information on the context so we can do fancy stuff in api2go with permissions. Each request would have a unique context. A global map[*request]context could be used but that is slow and in go 1.6 will panic if there isn't a mutex on it for reads and writes. The last brainstorm I had with my colleague we came to a conclusion of being able to register functions that create closures on contexts so any handlers would be able to support contexts.

I assume a `SetContext(c Context)` function would set the context globally which would break any other current request. I am going to take a look how gorilla uses contexts and see if can inspire myself another solution.

**Comment by sharpner** [comment]
The current behaviour has this method:
https://github.com/manyminds/api2go/blob/master/api.go#L190

It creates on new context for every request. 

It will then pass this context to all middlewares:
https://github.com/manyminds/api2go/blob/master/api.go#L183

Maybe I am not following your problem here, but this way, the first middleware can write stuff and the next middleware can use it, but it's on a per- request basis.
