### ISSUE TITLE
Recursive Loop

### ISSUE THREAD

**Issue by andymoon** [manyminds/api2go-adapter#7]
Isn't this line a recursive loop?

https://github.com/manyminds/api2go-adapter/blob/master/gingonic/gingonic.go#L15

**Comment by wwwdata** [comment]
I guess the go compiler automatically calls`g.router.Handler()` otherwise it would be a loop. Can you change that line and open a pr?

**Comment by andymoon** [comment]
Sure. I was also going to make an adapter for [Iris](https://github.com/kataras/iris).

**Comment by wwwdata** [comment]
cool :)
